---
title: "Harvard Course Enrollment Changes"
author: "Tanner Gildea"
date: "2/26/2019"
output: html_document
---

```{r setup, include = FALSE, echo = FALSE, results = "asis"}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(janitor)
library(readxl)
library(gt)

download.file(url = "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2.28.19.xlsx",
              destfile  = "~/Desktop/R.projects/class_2019-02-26/2019_data.xlsx",
              mode = "wb")    

download.file(url = "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_03.06.18.xlsx",
              destfile  = "~/Desktop/R.projects/class_2019-02-26/2018_data.xlsx",
              mode = "wb")     


enrollment_data_2019 <- read_excel("2019_data.xlsx", skip = 3) %>% 
  clean_names() %>% 
  filter(! is.na(course_name))

enrollment_data_2018 <- read_excel("2018_data.xlsx", skip = 3) %>% 
  clean_names() %>% 
  filter(! is.na(course_name))

fs::file_delete(c("2019_data.xlsx", "2018_data.xlsx"))

# number, name, 2018 enrollment, 2019 enrollment, arrange(desc(change))

joined_enrollment <- left_join(enrollment_data_2018, enrollment_data_2019, by = "course_id", suffix = c(".2018", ".2019")) %>% 
  filter(! is.na(total.2019)) %>% 
  mutate(enrollment_difference = (u_grad.2019 - u_grad.2018)) %>% 
  select(course_title.2018, course_name.2018, u_grad.2018, u_grad.2019, enrollment_difference) %>% 
  arrange(enrollment_difference) %>% 
  slice(1:10)

```

```{r table, echo = FALSE, results = "asis"}
gt(joined_enrollment) %>%
  tab_header(
    title = "Biggest Enrollment Decreases in Spring 2019") %>%
  
  cols_label(
    course_title.2018 = "Course Title",
    course_name.2018 = "Course Name",
    u_grad.2018 = "2018",
    u_grad.2019 = "2019",
    enrollment_difference = "Change") %>% 

as_raw_html() %>% as.character() %>% cat()

```




# Largest New Classes Spring 2019


``` {r next table, echo = FALSE, results = "asis"}
enrollment_data_2019 %>% 
  anti_join(enrollment_data_2018, by = "course_id") %>% 
  select(course_title, course_name, u_grad) %>% 
  arrange(desc(u_grad)) %>% 
  slice(1:10) %>% 
  
  gt() %>% 
  tab_header(
    title = "Largest New Classes Spring 2019") %>%
  
  cols_label(
    course_title = "Course Title",
    course_name = "Course Name",
    u_grad = "2019") %>% 
  
as_raw_html() %>% as.character() %>% cat()

